#Python Basics Assignment
#Python Basics Types,Expressinons and Variables,String Operations


In [1]:
#Python Basics Types,Expressinons and Variables,String Operations
#Types
a=1
print(type(a))
b=1.1
print(type(b))
c='string'
print(type(c))
d=True
print(type(d))
e=-1.1
print(type(e))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>
<class 'float'>


In [3]:
#Expressions and Variables
a=5
b=1
c=a+b
d=a+b-1
e=a+b-c*d
print(c)
print(d)
print(e)
f=a/b
g=a//b
h=a*b
i=a**a
j=a%b
print(f)
print(g)
print(h)
print(i)
print(j)

6
5
-24
5.0
5
5
3125
0


In [18]:
#String Operatins
string="Hello World"
string1=" My name is Raghu"
x=print(string+string1)
y=print(string*3)
len(string)
z=len(string)/len(string1)
print(z)

Hello World My name is Raghu
Hello WorldHello WorldHello World
0.6470588235294118


In [110]:
##Python DataStructures lists,tuples,Dictionaries,sets
#list
my_list=[20,10,5,10,20]
print(my_list)
#adding elements to my_list
my_list.append(3)#adding one element at last index
print(my_list)
my_list.extend([8,9])# adding multiple elements at last
print(my_list)
my_list.insert(2,7)# adding an element by specific index
print(my_list)
#removing elements
my_list.pop()#last element will be deleted
print(my_list)
my_list.remove(10)
print(my_list)# removes first occurrence of 10
my_list.pop(1)#removes by index number
print(my_list)
#concatenating two lists
my_list1=[5,5,5,5,5]
my_list2=[5,5,5,5,5]
m_list=list(my_list1+my_list2)
print(m_list)
#operations on lists
lst=my_list*5
print(lst)
#slicing and indexing
print(lst[0])
print(lst[0:])
print(lst[0:4])
print(lst[-1])
print(lst[-12:])
print(34 in lst)
#iterations 
for i in lst:
    print(i)
for i in lst:
    print(i*2)

[20, 10, 5, 10, 20]
[20, 10, 5, 10, 20, 3]
[20, 10, 5, 10, 20, 3, 8, 9]
[20, 10, 7, 5, 10, 20, 3, 8, 9]
[20, 10, 7, 5, 10, 20, 3, 8]
[20, 7, 5, 10, 20, 3, 8]
[20, 5, 10, 20, 3, 8]
[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
[20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8]
20
[20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8]
[20, 5, 10, 20]
8
[20, 5, 10, 20, 3, 8, 20, 5, 10, 20, 3, 8]
False
20
5
10
20
3
8
20
5
10
20
3
8
20
5
10
20
3
8
20
5
10
20
3
8
20
5
10
20
3
8
40
10
20
40
6
16
40
10
20
40
6
16
40
10
20
40
6
16
40
10
20
40
6
16
40
10
20
40
6
16


In [107]:
#dictionaries
my_dict={'name':'raghu',"age":26}
print(my_dict)
print(my_dict.values())## printing nly dict values
print(my_dict['name'])#accessing by key name
my_dict['name']='raj'#changing name 
print(my_dict)
my_dict1=my_dict.copy()#copying the dictionary
print(my_dict1)
my_dict.update({"name":'raghu','occupation':"SE"})#updating the dictionary
print(my_dict)
print(type(my_dict))
len(my_dict)
my_dict.pop('name')
print(my_dict)
print(my_dict.popitem())
print(my_dict1.items())
print(my_dict1.keys())
print(my_dict1.setdefault('age'))
my_dict.update({'name':'raghu','occupation':'SE'})
print(my_dict)
print(my_dict.get('age'))
my_dict.clear()
print(my_dict)
print(88 not in my_dict1)
for i in my_dict1.values():
    print(i)
for j in my_dict1:
    print(j)

{'name': 'raghu', 'age': 26}
dict_values(['raghu', 26])
raghu
{'name': 'raj', 'age': 26}
{'name': 'raj', 'age': 26}
{'name': 'raghu', 'age': 26, 'occupation': 'SE'}
<class 'dict'>
{'age': 26, 'occupation': 'SE'}
('occupation', 'SE')
dict_items([('name', 'raj'), ('age', 26)])
dict_keys(['name', 'age'])
26
{'age': 26, 'name': 'raghu', 'occupation': 'SE'}
26
{}
True
raj
26
name
age


In [114]:
#tuples same as lists but immutable 
tup=(1,2,3,4,5,1)
print(tup)
print(tup[0])
print(tup[0:])
print(tup[-1:])
print(tup)
print(tup*2)
tup1=(1,2,(3,4))
print(tup1)
print(tup1[2][1])
del tup
print(88 not in tup1)
for i in tup1:
    print(i)
for i in tup1:
    print(i*2)

(1, 2, 3, 4, 5, 1)
1
(1, 2, 3, 4, 5, 1)
(1,)
(1, 2, 3, 4, 5, 1)
(1, 2, 3, 4, 5, 1, 1, 2, 3, 4, 5, 1)
(1, 2, (3, 4))
4
True
1
2
(3, 4)
2
4
(3, 4, 3, 4)


In [130]:
# sets unordered cllection of elements with n duplicates 
set1={1,1,2,2,3,4,5}
print(set1)
print(type(set1))
set2={1,2,3,3,4,4,5,6,7,8}
print(set2)
print(set1|set2)
print(set1&set2)
print(set1-set2)
print(set1^set2)
days=set(['mon','tue'])
print(days)
print(type(days))
days.add("sun")
print(days)
days.discard("sun")
print(days)
print(set1>=set2)

{1, 2, 3, 4, 5}
<class 'set'>
{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5, 6, 7, 8}
{1, 2, 3, 4, 5}
set()
{6, 7, 8}
{'tue', 'mon'}
<class 'set'>
{'tue', 'sun', 'mon'}
{'tue', 'mon'}
False


In [1]:
##python programing fundamentals
#conditions and branching in python
if True:
    print("Hello world")
if False:
    print("Hello ")
a=1
if a<=1:
    print("a is less tahn or equal to 1")
else:
    print("a is greater than 1")
pwd='hello'
a=input("enter your password")
if a==pwd:
    print("welcome")
else:
    print("retry your password")
x=12
if x<10:
    print("x less than 10")
elif x<15:
    print("x less than 15")
else:
    print("x greater than or equal to 15")

Hello world
a is less tahn or equal to 1
enter your passwordhello
welcome
x less than 15


In [2]:
#while loop
i=1
while i<=5:
    i+=1
    print(i)

2
3
4
5
6


In [3]:
#for loop
l=[1,2,3]
for i in l:
    print(i)

1
2
3


In [8]:
x=[i*2 for i in range(5)]
x

[0, 2, 4, 6, 8]

In [10]:
#lambda function
sum=lambda a,b:a+b
sum(1,2)

3

In [2]:
#functions 
def add():
    a=1
    b=2
    c=a+b
    return c
print(add())#same output for any 
def add1(a,b):
    c=a+b
    return c
print(add1(3,4))#gives based on ur passed values

def add2(a,*b):
    for i in b:
        c=a+i
        d=a+c
    return d
print(add2(2,2,12))


3
7
16


In [27]:
#objects and classes
class book:
    def __init__(self,author,published_year):
        self.author=author
        self.published_year=published_year
    def my_func(self):
        print("The author of the book is ",self.author," and the book is published in the year ",self.published_year)
my_book=book("raghu",2020)#object creation
my_book.author#accesing the object or initiating through dot notation
my_book.published_year
my_book.author='ram'
print(my_book.author)
my_book.my_func()
del my_book.author
my_book.author

ram
The author of the book is  ram  and the book is published in the year  2020


In [31]:
#working with data in python
#reading files
fo=open("df1.csv","r")
fo.write("hello sam how are u")
fo.close()

UnsupportedOperation: not writable

In [32]:
f=open("sample.txt",'w')
f.write("hello this is sample writing text file")
f.close()

In [37]:
f1=open('sample.txt','r')
print(f1)
f1.close()

<_io.TextIOWrapper name='sample.txt' mode='r' encoding='cp1252'>


In [43]:
#pandas
import pandas as pd
df=pd.read_csv('test_df.csv')
df.head()

Unnamed: 0   0   1   2   3
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15
4           4  16  17  18  19

In [46]:
type(df)

pandas.core.frame.DataFrame

In [47]:
df['0'].unique()

array([ 0,  4,  8, 12, 16], dtype=int64)

In [48]:
df[['0','1']].value_counts()

0   1 
16  17    1
12  13    1
8   9     1
4   5     1
0   1     1
dtype: int64

In [51]:
df['0']=[1,2,3,4,4]

In [52]:
df.head()

Unnamed: 0  0   1   2   3
0           0  1   1   2   3
1           1  2   5   6   7
2           2  3   9  10  11
3           3  4  13  14  15
4           4  4  17  18  19

In [54]:
df.iloc[1]

Unnamed: 0    1
0             2
1             5
2             6
3             7
Name: 1, dtype: int64

In [55]:
df.iloc[2]=[1,1,1,1,1]

In [57]:
df.shape

(5, 5)

In [58]:
df.ndim

2

In [59]:
df.corr()

Unnamed: 0         0         1         2         3
Unnamed: 0    1.000000  0.943023  0.971537  0.957926  0.942809
0             0.943023  1.000000  0.980038  0.980715  0.978945
1             0.971537  0.980038  1.000000  0.998651  0.994937
2             0.957926  0.980715  0.998651  1.000000  0.998813
3             0.942809  0.978945  0.994937  0.998813  1.000000

In [60]:
df.describe()

Unnamed: 0         0          1          2          3
count    5.000000  5.000000   5.000000   5.000000   5.000000
mean     1.800000  2.400000   7.400000   8.200000   9.000000
std      1.643168  1.516575   7.266361   7.496666   7.745967
min      0.000000  1.000000   1.000000   1.000000   1.000000
25%      1.000000  1.000000   1.000000   2.000000   3.000000
50%      1.000000  2.000000   5.000000   6.000000   7.000000
75%      3.000000  4.000000  13.000000  14.000000  15.000000
max      4.000000  4.000000  17.000000  18.000000  19.000000

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  5 non-null      int64
 1   0           5 non-null      int64
 2   1           5 non-null      int64
 3   2           5 non-null      int64
 4   3           5 non-null      int64
dtypes: int64(5)
memory usage: 328.0 bytes


In [62]:
df.isna()

Unnamed: 0      0      1      2      3
0       False  False  False  False  False
1       False  False  False  False  False
2       False  False  False  False  False
3       False  False  False  False  False
4       False  False  False  False  False

In [63]:
df.notna()

Unnamed: 0     0     1     2     3
0        True  True  True  True  True
1        True  True  True  True  True
2        True  True  True  True  True
3        True  True  True  True  True
4        True  True  True  True  True

In [74]:
df[df['1']>3]

Unnamed: 0  0   1   2   3
1           1  2   5   6   7
3           3  4  13  14  15
4           4  4  17  18  19

In [75]:
df[0:]

Unnamed: 0  0   1   2   3
0           0  1   1   2   3
1           1  2   5   6   7
2           1  1   1   1   1
3           3  4  13  14  15
4           4  4  17  18  19

In [81]:
df[1:]

Unnamed: 0  0   1   2   3
1           1  2   5   6   7
2           1  1   1   1   1
3           3  4  13  14  15
4           4  4  17  18  19

In [90]:
#numpy
import numpy as np
a=[1,2,3,4]
print(type(a))
a=np.array(a)
print(type(a))
a
print(np.shape(a))
print(np.size(a))

<class 'list'>
<class 'numpy.ndarray'>
(4,)
4


In [97]:

b=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(type(b))
print(np.shape(b))
print(np.size(b))


<class 'numpy.ndarray'>
(2, 5)
10


In [140]:
c=np.arange(0,20).reshape(4,5)
print(c)
print(type(c))
print(np.shape(c))
print(np.size(c))
print(np.ndim(c))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
(4, 5)
20
2


In [142]:
print(c[0])
print(c[1][2])
print(c[0:,1:])

print(c[1:2,1:])

[0 1 2 3 4]
7
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]
[[6 7 8 9]]


In [113]:
a=np.random.rand(10).reshape(2,5)
a

array([[0.24885383, 0.23755539, 0.02110313, 0.66090115, 0.01467818],
       [0.68633771, 0.77853867, 0.01278059, 0.45560114, 0.69609401]])

In [120]:
b=np.random.randint(0,100,10).reshape(2,5)
b

array([[92, 49, 17, 78, 26],
       [36,  8, 34, 74, 32]])

In [124]:
c=np.random.randn(10)
c

array([-0.21684546, -0.65511625, -0.12101983, -0.31862516,  1.79480468,
       -0.01226899, -0.44474759,  1.3065078 , -0.06180739, -1.46079989])

In [134]:
np.ndim(c)
np.shape(c)

(10,)